Models/Presupuesto.cs
using espacioPresupuestosDetalle;
using espacioProducto;
using System.Linq;

namespace espacioPresupuestos;

public class Presupuesto
{
    private int idPresupuesto;
    private string? nombreDestinatario;
    private string? fechaCreacion;
    private List<PresupuestoDetalle> detalle;

    const double IVA = 0.21;
    public int IdPresupuesto { get => idPresupuesto; set => idPresupuesto = value; }
    public string? NombreDestinatario { get => nombreDestinatario; set => nombreDestinatario = value; }
    public List<PresupuestoDetalle> Detalle { get => detalle; }
    public string? FechaCreacion { get => fechaCreacion; set => fechaCreacion = value; }

    public Presupuesto()
    {
        detalle = new List<PresupuestoDetalle>();
    }
    public void AgregarProducto(Producto nuevoProducto, int cantidadProducto)
    {
        PresupuestoDetalle nuevoPresupuestoDetalle = new PresupuestoDetalle();
        nuevoPresupuestoDetalle.CargarProducto(nuevoProducto);
        nuevoPresupuestoDetalle.Cantidad = cantidadProducto;

    }
    public double MontoPresupuesto()
    {
        int monto = 0;
        foreach (PresupuestoDetalle detalle in Detalle)
        {
            monto += detalle.Producto.Precio * detalle.Cantidad;
        }

        return monto;
    }
    public double MontoPresupuestoConIVA()
    {
        return MontoPresupuesto()*(1+IVA);
    }

    public int CantidadProductos()
    {
        return Detalle.Count();
    }
    public void CargarDetallesPresupuesto(List<PresupuestoDetalle> presupuestoDetalles)
    {
        detalle=presupuestoDetalles;
        foreach (var presupuestoDetalle in detalle)
        {
            presupuestoDetalle.IdPresupuesto=idPresupuesto;
        }
    }
}

Models/Presupuestos.cs
using espacioPresupuestosDetalle;
using espacioProducto;
using System.Linq;

namespace espacioPresupuestos;

public class Presupuesto
{
    private int idPresupuesto;
    private string nombreDestinatario;
    private string fechaCreacion;
    private List<PresupuestoDetalle> detalle;

    const int IVA = 21;
    public int IdPresupuesto { get => idPresupuesto; set => idPresupuesto = value; }
    public string NombreDestinatario { get => nombreDestinatario; set => nombreDestinatario = value; }
    public List<PresupuestoDetalle> Detalle { get => detalle; }
    public string FechaCreacion { get => fechaCreacion; set => fechaCreacion = value; }

    public Presupuesto()
    {
        detalle = new List<PresupuestoDetalle>();
    }
    public void AgregarProducto(Producto nuevoProducto, int cantidadProducto)
    {
        PresupuestoDetalle nuevoPresupuestoDetalle = new PresupuestoDetalle();
        nuevoPresupuestoDetalle.CargarProducto(nuevoProducto);
        nuevoPresupuestoDetalle.Cantidad = cantidadProducto;

    }
    public int MontoPresupuesto()
    {
        int monto = 0;
        foreach (PresupuestoDetalle detalle in Detalle)
        {
            monto += detalle.Producto.Precio * detalle.Cantidad;
        }

        return monto;
    }
    public int MontoPresupuestoConIVA()
    {
        int monto = 0;
        foreach (PresupuestoDetalle detalle in Detalle)
        {
            monto += detalle.Producto.Precio * detalle.Cantidad * IVA;
        }

        return monto;
    }

    public int CantidadProductos()
    {
        return Detalle.Count();
    }
    public void CargarDetallesPresupuesto(List<PresupuestoDetalle> presupuestoDetalles)
    {
        detalle=presupuestoDetalles;
    }
}

Controllers/PresupuestoController.cs
using System.Diagnostics;
using espacioPresupuestos;
using espacioProducto;
using espacioPresupuestoRepository;
using espacioProductoRepository;
using Microsoft.AspNetCore.Mvc;
using SQLitePCL;
using tl2_tp6_2024_GonzaSanPla.Models;
using espacioPresupuestosDetalle;

namespace tl2_tp6_2024_GonzaSanPla.Controllers;

public class PresupuestoController : Controller
{
    private readonly ILogger<HomeController> _logger;
    PresupuestoRepository presupuestoRepository = new PresupuestoRepository();
    ProductoRepository productoRepository = new ProductoRepository();


    public PresupuestoController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    [HttpGet]
    public ActionResult<List<Presupuesto>> Index()
    {
        return View(presupuestoRepository.ListarPresupuestos());
    }
    [HttpGet]
    public IActionResult CrearPresupuesto()
    {
        return View();
    }

    [HttpPost]
    public IActionResult CrearPresupuesto(Presupuesto presupuesto)
    {
        presupuestoRepository.CrearNuevoPresupuesto(presupuesto);
        return RedirectToAction("Index");
    }
    [HttpGet]
    public IActionResult ModificarPresupuesto(int id)
    {
        return View(presupuestoRepository.ObtenerPresupuestoPorId(id));
    }

    [HttpPost]
    public IActionResult ModificarPresupuesto(int id, Presupuesto presupuesto)
    {
        presupuestoRepository.ModificarPresupuesto(id, presupuesto);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult EliminarPresupuesto(int id)
    {
        return View(presupuestoRepository.ObtenerPresupuestoPorId(id));
    }

    public IActionResult ConfirmarEliminacion(int id)
    {
        presupuestoRepository.EliminarPresupuesto(id);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult MostrarPresupuestoDetalle(int id)
    {
        return View(presupuestoRepository.ListarDetallePresupuesto(id));
    }
    
    [HttpGet]
    public IActionResult AgregarProducto(int id)
    {
        PresupuestoDetalle presupuestoDetalle=new PresupuestoDetalle();
        presupuestoDetalle.IdPresupuesto=id;
        return View(presupuestoDetalle);
    }

    [HttpPost]
    public IActionResult AgregarProducto(PresupuestoDetalle presupuestoDetalle)
    {
        presupuestoRepository.CrearNuevoDetalle(presupuestoDetalle);
        return RedirectToAction("Index");
    }
}

Controllers/ProductoController.cs
using System.Diagnostics;
using espacioProducto;
using espacioProductoRepository;
using Microsoft.AspNetCore.Mvc;
using SQLitePCL;
using tl2_tp6_2024_GonzaSanPla.Models;

namespace tl2_tp6_2024_GonzaSanPla.Controllers;

public class ProductoController : Controller
{
    private readonly ILogger<HomeController> _logger;
    ProductoRepository productoRepository = new ProductoRepository();

    public ProductoController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    [HttpGet]
    public ActionResult<List<Producto>> Index()
    {
        return View(productoRepository.ListarProductos());
    }
    [HttpGet]
    public IActionResult CrearProducto()
    {
        return View();
    }

    [HttpPost]
    public IActionResult CrearProducto(Producto producto)
    {
        productoRepository.CrearNuevo(producto);
        return RedirectToAction("Index");
    }
    [HttpGet]
    public IActionResult ModificarProducto(int id)
    {
        return View(productoRepository.ObtenerProductoPorId(id));
    }

    [HttpPost]
    public IActionResult ModificarProducto(int id, Producto producto)
    {
        productoRepository.ModificarProducto(id, producto);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult EliminarProducto(int id)
    {
        return View(productoRepository.ObtenerProductoPorId(id));
    }


    // [HttpGet]
    // public IActionResult EliminarProducto(int id,bool confirmar)
    // {
    //     if(confirmar)
    //     {
    //         productoRepository.EliminarProducto(id);
    //     }
    //     return RedirectToAction("Index");
    // }


    // [HttpPost] No va Post porque recibe objeto formulario nomas
    public IActionResult ConfirmarEliminacion(int id)
    {
        productoRepository.EliminarProducto(id);
        return RedirectToAction("Index");
    }


    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Presupuesto/AgregarProducto.cshtml
@{
    ViewData["Title"] = "AgregarProducto";
}

@model espacioPresupuestosDetalle.PresupuestoDetalle

<form asp-controller="Presupuesto" asp-action="AgregarProducto">
  <div class="mb-3">
    <input hidden asp-for="@Model.IdPresupuesto">
    <label asp-for=@Model.Producto.IdProducto class="form-label">ID Producto</label>
    <input asp-for=@Model.Producto.IdProducto type="number" class="form-control">
    <label asp-for=@Model.Cantidad class="form-label">Cantidad</label>
    <input asp-for=@Model.Cantidad type="number" class="form-control">
  </div>    
  <button type="submit" class="btn btn-outline-success">Crear</button>
</form>    

Views/Presupuesto/ConfirmarEliminacion.cshtml
@{
  ViewData["Title"] = "ConfirmarEliminacion";
  
}

@model espacioProducto.Producto

<div class="text-center">
  <h2>¿Seguro que desea eliminar el siguiente producto?</h2>
</div>
<table class="table table-danger table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Precio</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">@Model.IdProducto</th>
      <td>@Model.Descripcion</td>
      <td>@Model.Precio</td>
    </tr>
  </tbody>
</table>

<button type="button" class="btn btn-success"><a class="nav-link text-light" asp-area="" asp-controller="Producto" asp-action="ConfirmarElimincaion" asp-route-id="@Model.IdProducto" >Confirmar</a></button> @*Se pude utilizar solo uno?*@
<button type="button" class="btn btn-danger"><a class="nav-link text-light" asp-area="" asp-controller="Producto" asp-action="Index" asp-route-id="@Model.IdProducto">Denegar</a></button>

Views/Presupuesto/CrearPresupuesto.cshtml
@{
    ViewData["Title"] = "CrearPresupuesto";
}

@model espacioPresupuestos.Presupuesto

<form asp-controller="Presupuesto" asp-action="CrearPresupuesto">
  <div class="mb-3">
    <label asp-for=@Model.NombreDestinatario class="form-label">Nombre destinatario</label>
    <input asp-for=@Model.NombreDestinatario type="text" class="form-control">
    @* Como poner Fecha actual? *@
    <label asp-for=@Model.FechaCreacion class="form-label">Fecha creación</label>
    <input asp-for=@Model.FechaCreacion type="date" class="form-control">
  </div>    
  <button type="submit" class="btn btn-outline-success">Crear</button>
</form>

Views/Presupuesto/EliminarPresupuesto.cshtml
@{
  ViewData["Title"] = "EliminarPresupuesto";

}

@model espacioPresupuestos.Presupuesto

<div class="text-center">
  <h2>¿Seguro que desea eliminar el siguiente presupuesto?</h2>
</div>
<table class="table table-danger">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre destinatario</th>
      <th scope="col">Fecha de creación</th>
      <th scope="col">Monto total</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">@Model.IdPresupuesto</th>
      <td>@Model.NombreDestinatario</td>
      <td>@Model.FechaCreacion</td>
      <td>$@Model.MontoPresupuestoConIVA()</td>
    </tr>
  </tbody>
</table>

<button type="button" class="btn btn-success"><a class="nav-link text-light" asp-area="" asp-controller="Presupuesto" asp-action="ConfirmarEliminacion" asp-route-id="@Model.IdPresupuesto">Confirmar</a></button> 
<button type="button" class="btn btn-danger"><a class="nav-link text-light" asp-area="" asp-controller="Presupuesto" asp-action="Index">Denegar</a></button>

Views/Presupuesto/Index.cshtml
@{
    ViewData["Title"] = "Presupuesto";
}


@model List<espacioPresupuestos.Presupuesto> 

<div class="text-center">
    <h1 class="display-4">Listado de presupuesto</h1>
</div>
<table class="table table-primary table-striped">
    <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre destinatario</th>
      <th scope="col">Fecha de creación</th>
      <th scope="col">Monto total</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    using espacioPresupuestos;
    @foreach(var presupuesto in Model)
    {
        <tr>
            <th scope="row">@presupuesto.IdPresupuesto</th>
            <td>@presupuesto.NombreDestinatario</td>
            <td>@presupuesto.FechaCreacion</td>
            <td>$@presupuesto.MontoPresupuestoConIVA()</td>
            <td><button type="button" class="btn btn-primary"><a class="nav-link text-light" asp-area="" asp-controller="Presupuesto" asp-action="ModificarPresupuesto" asp-route-id="@presupuesto.IdPresupuesto">Modificar</a></button></td>
            <td><button type="button" class="btn btn-danger"><a class="nav-link text-light" asp-area="" asp-controller="Presupuesto" asp-action="EliminarPresupuesto" asp-route-id="@presupuesto.IdPresupuesto">Eliminar</a></button></td>
            <td><button type="button" class="btn btn-info"><a class="nav-link text-light" asp-area="" asp-controller="Presupuesto" asp-action="MostrarPresupuestoDetalle" asp-route-id="@presupuesto.IdPresupuesto">Detalle</a></button></td>
            <td><button type="button" class="btn btn-success"><a class="nav-link text-light" asp-area="" asp-controller="Presupuesto" asp-action="AgregarProducto" asp-route-id="@presupuesto.IdPresupuesto">Agregar Producto</a></button></td>
        </tr>
    }
  </tbody>
</table>
<div class="text-center">
    <button type="button" class="btn btn-success"><a   class="nav-link text-light" asp-area="" asp-controller="Presupuesto" asp-action="CrearPresupuesto">Agregar presupuesto a la lista</a></button>
</div>

Views/Presupuesto/ModificarPresupuesto.cshtml
@{
    ViewData["Title"] = "ModificarPresupuesto";
}

@model espacioPresupuestos.Presupuesto

<form asp-controller="Presupuesto" asp-action="ModificarPresupuesto">
  <div class="mb-3">
    <label asp-for=@Model.NombreDestinatario class="form-label">NombreDestinatario</label>
    <input asp-for=@Model.NombreDestinatario type="text" class="form-control">
    <label asp-for=@Model.FechaCreacion class="form-label">FechaCreacion</label>
    <input asp-for=@Model.FechaCreacion type="date" class="form-control">
  </div>    
  <button type="submit" class="btn btn-outline-success">Actualizar</button>
</form>

Views/Presupuesto/MostrarPresupuestoDetalle.cshtml
@{
  ViewData["Title"] = "MostrarPresupuestoDetalle";
}


@model List<espacioPresupuestosDetalle.PresupuestoDetalle>

<div class="text-center">
  <h1 class="display-4">Listado de presupuesto detalle de Producto</h1>
</div>
<table class="table table-primary table-striped">
  <thead>
    <tr>
      <th scope="col">ID Producto</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Precio</th>
      <th scope="col">Cantidad</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var presupuestoDetalle in Model)
    {
      <tr>
        <th scope="row">@presupuestoDetalle.Producto.IdProducto</th>
        <td>@presupuestoDetalle.Producto.Descripcion</td>
        <td>@presupuestoDetalle.Producto.Precio</td>
        <td>@presupuestoDetalle.Cantidad</td>
      </tr>
    }
  </tbody>
</table>